# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-16 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='name',
            new_name='typein',
        ),
        migrations.AddField(
            model_name='test',
            name='short_name',
            field=models.CharField(default=b'SOME STRING', max_length=256),
        ),
    ]
